---
# aptキャッシュupdate & upgrade
# 基本パッケージのインストール
# タイムゾーン設定
# 時刻同期設定
# ネットワーク設定

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    upgrade: full

- name: install basic packages
  ansible.builtin.apt: 
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: true
  loop: "{{ apt_basic_packages }}"

- name: timezone setup to "{{ datetime_timezone }}"
  community.general.timezone:
    name: "{{ datetime_timezone }}"

- name: configure timesyncd
  ansible.builtin.template:
    src: "{{ timesyncd_conf.src }}{{ timesyncd_conf.file }}.j2"
    dest: "{{ timesyncd_conf.dest }}{{ timesyncd_conf.file }}"
    owner: "{{ timesyncd_conf.owner }}"
    group: "{{ timesyncd_conf.group }}"
    mode: "{{ timesyncd_conf.mode }}"
  notify: Restart timesyncd service

- name: configre network (transfer netplan file)
  ansible.builtin.template:
    src: "{{ item.src }}{{ item.file }}.j2"
    dest: "{{ item.dest }}{{ item.file }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ netplan_yaml }}"
  notify: netplan apply

