---
- name: Add new user
  ansible.builtin.user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    state: "{{ item.state }}"
    create_home: "{{  item.create_home | default(defaultUbuntuUserset.create_home) }}"
    shell: "{{  item.shell | default(defaultUbuntuUserset.shell) }}"
    update_password: "{{  item.update_password | default(defaultUbuntuUserset.update_password) }}"
  loop: "{{ ubuntuUsers }}"
