---
- name: Deploy kubernetes cluster for u6s
  hosts: u6sCluster
  become: true
  roles:
    - role: ubuntuBasicSetup
      tags: ubuntuBasicSetup
    - role: linuxK8sSetup
      tags: linuxK8sSetup
    - role: linuxK8sBuild
      tags: linuxK8sBuild
