---
aptPackages:
  - name: chrony
    state: present
  - name: netplan.io
    state: present
  - name: containerd
    state: present
  - name: apt-transport-https
    state: present
  - name: ca-certificates
    state: present
  - name: curl
    state: present
  - name: gpg
    state: present
  - name: kubeadm
    state: present
    aptkey: true
    addrepo: true
    hold: true
  - name: kubectl
    state: present
    aptkey: true
    addrepo: true
    hold: true
  - name: kubelet
    state: present
    aptkey: true
    addrepo: true
    hold: true 
  - name: helm
    state: present
    aptkey: true
    addrepo: true

aptPackageDefault:
  state: present
  aptkey: false
  addrepo: false
  hold: false

aptKey:
  - name: kubeadm/kubectl/kubelet
    downloadURL: "https://pkgs.k8s.io/core:/stable:/v1.30/deb/"
    downloadKey: "Release.key"
    ascFile: "kubernetes-apt-keyring.asc"
    gpgFile: "kubernetes-apt-keyring.gpg"

  - name: helm
    downloadURL: "https://baltocdn.com/helm/"
    downloadKey: "signing.asc"
    ascFile: "helm-apt-keyring.asc"
    gpgFile: "helm-apt-keyring.gpg"

aptKeyDefault:
  dirPath: "/etc/apt/keyrings/"

aptRepo:
  - name: kubeadm/kubectl/kubelet
    file: "kubernetes.list"
  - name: helm
    file: "helm.list"

aptRepoDefault:
  src: "group_files/u6sMasters/repoList/"
  dest: "/etc/apt/sources.list.d/"
  owner: root
  group: root
  mode: '0644'
