---
defaultFileSet:
  src: "group_files/u6s-masters"
  owner: "root"
  group: "root"
  mode: '0644'

cloudInit:
  file: "cloud-init.disabled"
  path: "/etc/cloud/"

etcHosts:
  file: "hosts"
  src: "group_files/u6s-masters/"
  dest: "/etc/"
  owner: "root"
  group: "root"
  mode: '0644'

k8sDummyHosts:
  src: "{{ defaultFileSet.src }}/k8sDummyHosts.j2"
  dest: "/etc/hosts"

aptPackage:
  chronyConf:
    file: "chrony.conf"
    src: "group_files/u6s-masters/"
    dest: "/etc/chrony/"
    owner: "root"
    group: "root"
    mode: '0644'

modules_loadd:
  - file: "k8s.conf"
    src: "group_files/u6s-masters/modules_"
    dest: "/etc/modules-load.d/"
    owner: "root"
    group: "root"
    mode: '0644'

sysctld:
  - file: "k8s.conf"
    src: "group_files/u6s-masters/sysctl_"
    dest: "/etc/sysctl.d/"
    owner: "root"
    group: "root"
    mode: '0644'

fstabFile:
  file: "fstab"
  src: "group_files/u6s-masters/"
  dest: "/etc/"
  owner: "root"
  group: "root"
  mode: '0644'

k8sFile:
  kubeVIP:
    file: "kube-vip.yaml"
    src: "group_files/u6s-masters/"
    dest: "/etc/kubernetes/manifests/"
    owner: "root"
    group: "root"
    mode: '0644'
  adminConf:
    src: null # 自動生成
    dest: "/etc/kubernetes/admin.conf"
    mode: '0600'
  clusterJoin:
    file: "clusterJoin.info"
    src: null # 自動生成
    dest: "/etc/kubernetes/"
    mode: '0600'
  kubectlAuth:
    file: "config"
    src: "{{ k8sFile.adminConf.dest }}"
    dest: "/home/kubeope/.kube"
    owner: kubeope
    group: kubeope
    mode: '0775'
