---
defaultLinuxUsers:
  create_home: yes
  shell: /bin/bash
  password: >
    {{ lookup('community.hashi_vault.hashi_vault', 
    'secret=kv2/u6sMasters/data/everyone:password') }}
  update_password: on_create
  auth:
    kubectl: false
    ansible: false

linuxUsers:
  - name: kubeope
    state: present
    auth:
      kubectl: true
  - name: ansible
    state: present
    auth:
      kubectl: true
      ansible: true
