---
- name: apply kube-vip rbac no.1
  ansible.builtin.command:
    cmd: kubectl apply -f https://kube-vip.io/manifests/rbac.yaml
  register: kubectlRst

- name: debug first apply
  ansible.builtin.debug:
    msg: "{{ kubectlRst }}"

- name: apply kube-vip rbac no.2
  ansible.builtin.command:
    cmd: kubectl apply -f https://kube-vip.io/manifests/rbac.yaml
  register: kubectlRst2

- name: debug second apply
  ansible.builtin.debug:
    msg: "{{ kubectlRst2 }}"