---
# if ubuntu_k8s_setup task does not execute, you need to remove commentout.
# - name: Add k8s operation User
#   ansible.builtin.import_tasks: roles/ubuntuBasicSetup/tasks/user.yml
#   when vars[k8s.master.nodeGrp] in group_names

- name: make directory (/home/targetUser/.kube)
  ansible.builtin.file:
    path: /home/{{ item.name }}/.kube
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  when: (item.auth.kubectl | default(false)) and (k8s.master.nodeGrp in group_names)
  loop: "{{ linuxUsers }}"

- name: Add kubectl authority
  ansible.builtin.shell: |
    if [ ! -f /home/{{ item.name }}/.kube/{{ k8sFile.kubectlAuth.file }} ] || ! cmp -s {{ k8sFile.kubectlAuth.src }} /home/{{ item.name }}/.kube/{{ k8sFile.kubectlAuth.file }}; then
      cp {{ k8sFile.kubectlAuth.src }} /home/{{ item.name }}/.kube/{{ k8sFile.kubectlAuth.file }}
      chown {{ item.name }}:{{ item.name }} /home/{{ item.name }}/.kube/{{ k8sFile.kubectlAuth.file }}
      echo /home/{{ item.name }}/.kube/{{ k8sFile.kubectlAuth.file }} is replaced.
    fi
  register: confCopyResult
  changed_when: confCopyResult.stdout != ''
  when: (item.auth.kubectl | default(false)) and (k8s.master.nodeGrp in group_names)
  loop: "{{ linuxUsers }}"
