---
- name: apply kube-vip rbac no.1
  ansible.builtin.command:
    cmd: kubectl apply -f https://kube-vip.io/manifests/rbac.yaml
  become: true
  become_user: "{{ linuxUsers.0.name }}"
  changed_when: false
  register: kubectlRst

- name: check changed / unchanged rbac
  ansible.builtin.debug:
    msg: "kube-vip rbac is changed."
  changed_when: true
  when: not (' unchanged' in kubectlRst.stdout) 

