---
# kubernetesクラスタビルドtargetフラグ　allノードで検証->statモジュール
- name: Build target node search
  ansible.builtin.stat:
    path: "{{ k8sFile.kubectlAuth.src }}"
  register: k8sBuilded

# マスターノードのk8sクラスタjoinフラグ初期化 代表マスターノード以外のマスターノード
- name: Set fact master node controle plain join required. (initialize)
  ansible.builtin.set_fact:
    masterJoinReq: false
  run_once: true

# マスターノードのk8sクラスタjoinフラグのセット
- name: Set fact master node controle plain join required. 
  ansible.builtin.set_fact:
    masterJoinReq: true
  when: (inventory_hostname != k8s.master.repNode) and (not hostvars[item].k8sBuilded.stat.exists)
  loop: "{{ groups[k8s.master.nodeGrp] }}"
  run_once: true

# ワーカーノードのk8sクラスタjoinフラグ初期化
- name: Set fact worker node k8s cluster join required. (initialize)
  ansible.builtin.set_fact:
    wokerJoinReq: false
  run_once: true

# ワーカーノードのk8sクラスタjoinフラグセット
- name: Set fact worker node k8s cluster join required. 
  ansible.builtin.set_fact:
    workerJoinReq: true
  when: not hostvars[item].k8sBuilded.stat.exists
  loop: "{{ groups[k8s.worker.nodeGrp] }}"
  run_once: true

# allノードで実行
- name: configure {{ etcHosts.dest }}{{ etcHosts.file }}
  ansible.builtin.template:
    src: "{{ etcHosts.src }}{{ etcHosts.file }}.j2"
    dest: "{{ etcHosts.dest }}{{ etcHosts.file }}"
    owner: "{{ etcHosts.owner }}"
    group: "{{ etcHosts.group }}"
    mode: "{{ etcHosts.mode }}"

# マスターノードで実行
- name: configure {{ k8sFile.kubeVIP.dest }}{{ k8sFile.kubeVIP.file }}
  ansible.builtin.template:
    src: "{{ k8sFile.kubeVIP.src }}{{ k8sFile.kubeVIP.file }}.j2"
    dest: "{{ k8sFile.kubeVIP.dest }}{{ k8sFile.kubeVIP.file }}"
    owner: "{{ k8sFile.kubeVIP.owner }}"
    group: "{{ k8sFile.kubeVIP.group }}"
    mode: "{{ k8sFile.kubeVIP.mode }}"
  when: k8s.master.nodeGrp in group_names

# 代表マスターノードで実行
- name: Initialize Kubernetes master (represent master node only)
  ansible.builtin.command:
    cmd: >
      kubeadm init 
      --control-plane-endpoint {{ k8s.network.vhost }}:{{ k8s.network.port}} 
      --pod-network-cidr={{ k8s.network.cidr }} 
      --upload-certs
  when: (inventory_hostname == k8s.master.repNode) and (not k8sBuilded.stat.exists)
        
# representマスター以外のマスターノード・ワーカーノードの1台以上がjoin未済だった場合
- name: k8s token create on represent master node
  ansible.builtin.command: 
    cmd: kubeadm token create --print-join-command
  register: k8sJoin
  when: (inventory_hostname == k8s.master.repNode) and (masterJoinReq or workerJoinReq)

- name: kubeadm join command set
  ansible.builtin.set_fact:
    kubeadmJoin: "{{ k8sJoin.stdout }}"
  run_once: true
  when: (inventory_hostname == k8s.master.repNode) and (masterJoinReq or workerJoinReq)

# representマスター以外のマスターノードの1台以上がjoin未済だった場合
- name: exec kubeadm init phase upload-certs --upload-certs
  ansible.builtin.command: 
    cmd: kubeadm init phase upload-certs --upload-certs
  register: k8sCertOutput
  when: (inventory_hostname == k8s.master.repNode) and masterJoinReq

- name: get k8s certs
  ansible.builtin.set_fact:
    k8sCertKey: "{{ k8sCertOutput.stdout_lines[-1] }}"
  run_once: true
  when: (inventory_hostname == k8s.master.repNode) and masterJoinReq

- name: exec "kubeadm join" on master node
  ansible.builtin.command:
    cmd: "{{ kubeadmJoin }} --control-plane --certificate-key {{ k8sCertKey }}"
  when: (inventory_hostname != k8s.master.repNode) and (not k8sBuilded.stat.exists) and (k8s.master.nodeGrp in group_names)

- name: exec "kubeadm join" on worker node
  ansible.builtin.command:
    cmd: "{{ kubeadmJoin }}"
  when: (not k8sBuilded.stat.exists) and (k8s.worker.nodeGrp in group_names)

# if ubuntu_k8s_setup task does not execute, you need to remove commentout.
# - name: Add k8s operation User
#   ansible.builtin.import_tasks: roles/ubuntuBasicSetup/tasks/user.yml
#   when vars['k8s.master.nodeGrp'] in group_names

- name: make directory (/home/targetUser/.kube)
  ansible.builtin.file:
    path: /home/{{ item.name }}/.kube
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  when: item.auth.kubectl  and (vars['k8s.master.nodeGrp'] in group_names)
  loop: "{{ linuxUsers }}"

- name: Add kubectl authority
  ansible.builtin.shell: |
    if [ ! -f /home/{{ item.name }}/.kube/{{ k8sFile.kubectlAuth.file }} ] || ! cmp -s {{ k8sFile.kubectlAuth.src }} /home/{{ item.name }}/.kube/{{ k8sFile.kubectlAuth.file }}; then
      cp {{ k8sFile.kubectlAuth.src }} /home/{{ item.name }}/.kube/{{ k8sFile.kubectlAuth.file }}
      chown {{ item.name }}:{{ item.name }} /home/{{ item.name }}/.kube/{{ k8sFile.kubectlAuth.file }}
      echo /home/{{ item.name }}/.kube/{{ k8sFile.kubectlAuth.file }} is replaced.
    fi
  register: confCopyResult
  changed_when: confCopyResult.stdout != ''
  when: item.auth.kubectl and (vars['k8s.master.nodeGrp'] in group_names)
  loop: "{{ linuxUsers }}"

# 任意のCNIを利用できるようにCNIインストールはtaskを切り出し。
- name: CNI=cilium install
  ansible.builtin.import_tasks: cilium.yml
