---
# ubuntu->apt install -y nfs-common
# almalinux->dnf install -y nfs-utils

# if you do not execute package install task, you remove this commentout
## if almalinux 
# - name: install dnf packages
#   ansible.builtin.import_tasks: roles/almaBasicSetup/tasks/dnf.yml
## if ubuntu
# - name: install apt packages
#   ansible.builtin.import_tasks: roles/ubuntuBasicSetup/tasks/apt.yml

# nfsマウントポイント用ディレクトリの作成
- name: create directory for nfs mount point
  ansible.builtin.file:
    path:  "{{ item.name }}"
    state: "{{ item.state | default(defDir.state) }}"
    owner: "{{ item.owner | default(defDir.owner) }}"
    group: "{{ item.group | default(defDir.group) }}"
    mode:  "{{ item.mode  | default(defDir.mode) }}"
  loop: "{{ directories.nfsMntPt }}"

- name: mount nfs devices
  ansible.posix.mount:
    path: "{{ item.path }}"
    src:  "{{ item.src }}"
    fstype: "{{ item.fstype | default(mountDef) }}"
    opts:   "{{ item.opts | default(mountDef) }}"
    state:  "{{ item.state | default(mountDef)}}"
  loop: "{{ mountPoint.nfs }}"

# nfsデータ共有用ディレクトリの作成
# セキュリティ上、ユーザ単位にデータ領域を作成する目的
- name: create directory for nfs data sharing
  ansible.builtin.file:
    path:  "{{ item.name }}"
    state: "{{ item.state | default(defDir.state) }}"
    owner: "{{ item.owner | default(defDir.owner) }}"
    group: "{{ item.group | default(defDir.group) }}"
    mode:  "{{ item.mode  | default(defDir.mode) }}"
  become_user: "{{ item.owner }}"
  loop: "{{ directories.nfsData }}"
