---
# if you do not execute almaBasicSetup task, you remove this commentout
# - name: install dnf pakeages
#   ansible.builtin.import_tasks: roles/almaBasicSetup/tasks/dnf.yml

- name: include disk partition create tasks
  ansible.builtin.include_tasks: diskPartitionCreate.yml
  when: >-
    (partBuildReq | default(false)) or 
    (raidConf4Build is defined | default(false))

- name: include raid1 build tasks
  ansible.builtin.include_tasks: raid1Build.yml
  when: >-
    (raid1BuildReq | default(false)) or 
    (raidConf4Build is defined | default(false))


