# このtaskを実行する場合、ansible実行ユーザにkubectl権限が付与されている必要がある。
# kubectl権限が付与されていない場合、cilium
---
- name: Check Cilium-cli installed
  ansible.builtin.command: which cilium
  register: ciliumChk
  ignore_errors: true
  changed_when: false

- name: Install cilium-cli
  when: cliumChk.rc != 0
  block:
    - name: Get Cilium CLI stable version
      ansible.builtin.uri:
        url: "{{ cni.cilium.CLI.latestVer }}"
        return_content: true
      register: ciliumCliVer
  
    - name: Set fact cpu architecture
      ansible.builtin.set_fact:
        cliArch: >
          {% if ansible_architecture == 'aarch64' %}
            arm64
          {% elif ansible_architecture == 'x86_64' %}
            amd64
          {% else %}
            Other
          {% endif %}

    - name: Fail if cpu architecture is Other
      ansible.builtin.fail:
        msg: "This CPU architecture is not supported."
      when: cliArch == 'Other'

    - name: Download Cilium CLI tarball
      block:
        - name: Cilium CLI tarball
          ansible.builtin.get_url:
            url: "https://github.com/cilium/cilium-cli/releases/download/{{ ciliumCliVer.content }}/cilium-linux-{{ cliArch }}.tar.gz"
            dest: "/tmp/cilium-linux-{{ cliArch }}.tar.gz"

        - name: Cilium CLI checksum
          ansible.builtin.get_url:
            url: "https://github.com/cilium/cilium-cli/releases/download/{{ ciliumCliVer.content }}/cilium-linux-{{ cliArch }}.tar.gz.sha256sum"
            dest: "/tmp/cilium-linux-{{ cliArch }}.tar.gz.sha256sum"

        - name: Verify checksum
          ansible.builtin.command:
            cmd: sha256sum --check cilium-linux-{{ cli_arch }}.tar.gz.sha256sum
            chdir: /tmp
          changed_when: false

    - name: Extract Cilium CLI
      ansible.builtin.unarchive:
        src: /tmp/cilium-linux-{{ cli_arch }}.tar.gz
        dest: "{{ cni.cilium.CLI.installPath }}"
        remote_src: true
        extra_opts: --gzip
        creates: "{{ cni.cilium.CLI.installPath }}/cilium"

    - name: Remove tarball and checksum
      ansible.builtin.file:
        path: /tmp/cilium-linux-{{ cli_arch }}.tar.gz{{ item }}
        state: absent
      changed_when: false
      loop:
        - ""
        - ".sha256sum"

- name: Cilium install on represent master node
  when: kubeadmInitNode == 'true'
  block:
    - name: Check cilium install status
      ansible.builtin.shell:
        cmd: kubectl get pods --namespace kube-system | ^grep cilium- 
      register: ciliumResult
      ignore_errors: true
      changed_when: false
      become_user: ansible

    - name: Install cilium
      when: ciliumResult.rc != 0
      block:
        - name: Get cilium stable version
          ansible.builtin.uri:
            url: "{{ cni.cilium.cilium.latestVer }}"
            return_content: true
          register: ciliumVer

        - name: cilium install --version {{ ciliumVer.content | regex_replace('^v', '') }}
          ansible.builtin.command:
            cmd: cilium install --version {{ ciliumVer.content | regex_replace('^v', '') }}
          become_user: ansible
