---
- name: Add k8s operation User
  ansible.builtin.import_tasks: roles/ubuntu_basic_setup/tasks/user.yml

- name: make directory ({{ k8sFile.kubectlAuth.dest }})
  ansible.builtin.file:
    path: "{{ k8sFile.kubectlAuth.dest }}"
    state: directory
    owner: "{{ k8sFile.kubectlAuth.owner | default(defaultFileSet.owner) }}"
    group: "{{ k8sFile.kubectlAuth.group | default(defaultFileSet.group) }}"
    mode: "{{ k8sFile.kubectlAuth.mode | default(defaultFileSet.mode) }}"

- name: Add kubectl authority
  ansible.builtin.shell: |
    if [ ! -f {{ k8sFile.kubectlAuth.dest }}/{{ k8sFile.kubectlAuth.file }} ] || ! cmp -s {{ k8sFile.kubectlAuth.src }} {{ k8sFile.kubectlAuth.dest }}/{{ k8sFile.kubectlAuth.file }}; then
      cp {{ k8sFile.kubectlAuth.src }} {{ k8sFile.kubectlAuth.dest }}/{{ k8sFile.kubectlAuth.file }}
      echo {{ k8sFile.kubectlAuth.dest }}/{{ k8sFile.kubectlAuth.file }} is replaced.
    fi
  register: confCopyResult
  changed_when: confCopyResult.stdout != ''
