---
- name: Initialize Kubernetes master
  when: kubeadmInitNode == 'true'
  block:
  - name: /etc/hosts changed (VIP is temporary changed.)
    ansible.builtin.template:
      src: "{{ k8sFile.dummyHosts.src }}"
      dest: "{{ k8sFile.dummyHosts.dest }}"
      owner: "{{ k8sFile.dummyHosts.owner | default(defaultFileSet.owner) }}"
      group: "{{ k8sFile.dummyHosts.group | default(defaultFileSet.group) }}"
      mode: "{{ k8sFile.dummyHosts.mode | default(defaultFileSet.mode) }}"

  - name: exec "kubeadm init" on master node
    ansible.builtin.command:
      cmd: >
        kubeadm init 
        --control-plane-endpoint {{ k8s.network.vhost }}:{{ k8s.network.port}} 
        --pod-network-cidr={{ k8s.network.cidr }} 
        --upload-certs
      creates: "{{ k8sFile.adminConf.dest }}"
    register: kubeInitResult

  - name: save k8s cluster join infomation file
    ansible.builtin.copy:
      content: "{{ kubeInitResult.stdout_lines }}"
      dest: "{{ k8sFile.clusterJoin.dest }}{{ k8sFile.clusterJoin.file }}"
      owner: "{{ clusterJoin.owner | default(defaultFileSet.owner) }}"
      group: "{{ clusterJoin.group | default(defaultFileSet.group) }}"
      mode: "{{ clusterJoin.mode | default(defaultFileSet.mode) }}"
    when: kubeInitResult.changed


  - name: Add k8s operation User
    ansible.builtin.import_tasks: roles/ubuntu_basic_setup/tasks/user.yml

  - name: make directory ({{ k8sFile.kubectlAuth.dest }})
    ansible.builtin.file:
      path: "{{ k8sFile.kubectlAuth.dest }}"
      state: directory
      owner: "{{ k8sFile.kubectlAuth.owner | default(defaultFileSet.owner) }}"
      group: "{{ k8sFile.kubectlAuth.group | default(defaultFileSet.group) }}"
      mode: "{{ k8sFile.kubectlAuth.mode | default(defaultFileSet.mode) }}"

  - name: Add kubectl authority
    ansible.builtin.shell: |
      if [ ! -f {{ k8sFile.kubectlAuth.dest }}/{{ k8sFile.kubectlAuth.file }} ] || ! cmp -s {{ k8sFile.kubectlAuth.src }} {{ k8sFile.kubectlAuth.dest }}/{{ k8sFile.kubectlAuth.file }}; then
        cp {{ k8sFile.kubectlAuth.src }} {{ k8sFile.kubectlAuth.dest }}/{{ k8sFile.kubectlAuth.file }}
        chown {{ k8sFile.kubectlAuth.owner }}:{{k8sFile.kubectlAuth.group }} {{ k8sFile.kubectlAuth.dest }}/{{ k8sFile.kubectlAuth.file }}
        echo {{ k8sFile.kubectlAuth.dest }}/{{ k8sFile.kubectlAuth.file }} is replaced.
      fi
    register: confCopyResult
    changed_when: confCopyResult.stdout != ''
  