---
- name: Initialize Kubernetes master
  ansible.builtin.command:
    cmd: >
      kubeadm init 
      --control-plane-endpoint {{ k8s.network.vhost }}:{{ k8s.network.port}} 
      --pod-network-cidr={{ k8s.network.cidr }} 
      --upload-certs
    creates: "{{ k8sFile.clusterJoin.dest }}{{k8sFile.clusterJoin.file }}"
  register: k8s_init
  
- name: Create kube config
  ansible.builtin.copy:
    content: "{{ k8s_init.stdout_lines }}"
    dest: "{{ k8sFile.clusterJoin.dest }}{{k8sFile.clusterJoin.file }}"
  args:
    creates: "{{ k8sFile.clusterJoin.dest }}{{k8sFile.clusterJoin.file }}"