---
- name: Copy the CA certificate
  ansible.builtin.copy:
    src: "{{ item.src | default(defaultFileSet.src) }}/{{ item.file }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default(defaultFileSet.owner) }}"
    group: "{{ item.group | default(defaultFileSet.group) }}"
    mode: "{{ item.mode | default(defaultFileSet.mode) }}"
  loop: "{{ certification }}"
  register: certCopy

- name: Update the CA certificates
  ansible.builtin.command: update-ca-certificates
  when: certCopy.results | selectattr('changed', 'equalto', true) | list | length > 0

- name: Verify the CA certificates are installed
  ansible.builtin.command: openssl x509 -in "{{ item.dest }}" -text -noout
  when: item.changed
  loop: "{{ certCopy.results }}"
  