---
# cloud-init無効か
# タイムゾーン設定
# aptキャッシュupdate & upgrade
# パッケージのインストール
# 時刻同期設定
# ネットワーク設定
# ユーザ設定

- name: Disable cloud-init
  ansible.builtin.file:
    path: "{{ cloudInit.path }}{{ cloudInit.file }}"
    state: touch
    access_time: preserve
    modification_time: preserve

- name: timezone setup to "{{ datetime_timezone }}"
  community.general.timezone:
    name: "{{ datetime_timezone }}"

- name: Update apt cache ans apt upgrade
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
    purge: true

- name: install packages
  ansible.builtin.import_tasks: apt.yml

- name: configure Chrony
  ansible.builtin.template:
    src: "{{ chronyService.src | default(defaultFileSet.src) }}/{{ chronyService.configFile }}.j2"
    dest: "{{ chronyService.configPath }}/{{ chronyService.configFile }}"
    owner: "{{ chronyService.owner | default(defaultFileSet.owner) }}"
    group: "{{ chronyService.group | default(defaultFileSet.group) }}"
    mode: "{{ chronyService.mode | default(defaultFileSet.mode) }}"
  register: chronyUpdate

- name: Restart chrony service
  ansible.builtin.systemd:
    name: chrony
    state: restarted
    enabled: true
  when: chronyUpdate.changed

- name: Rename builtin netplan file 
  block:
  - name: configure network (check currnet netplan filename)
    ansible.builtin.stat:
      path: "{{ item.dest }}/{{ item.file }}"
    register: file_stat
    loop: "{{ netplanBuiltin }}"

  - name: Rename netplan file
    ansible.builtin.command: mv "{{ item.1.dest }}/{{ item.1.file }}" "{{ item.1.dest }}/{{ item.1.file }}.org"
    when: item.0.stat.exists
    loop: "{{ file_stat.results | product(netplanBuiltin) }}"

- name: configure network (transfer netplan file)
  ansible.builtin.template:
    src: "{{ item.src | default(defaultFileSet.src) }}/{{ item.file }}.j2"
    dest: "{{ item.dest }}/{{ item.file }}"
    owner: "{{ item.owner | default(defaultFileSet.owner) }}"
    group: "{{ item.group | default(defaultFileSet.group) }}"
    mode: "{{ item.mode | default(defaultFileSet.mode) }}"
  loop: "{{ netplan }}"
  register: netplanUpdate

- name: netplan apply
  ansible.builtin.command: "netplan apply --debug"
  when: netplanUpdate.results | selectattr('changed', 'equalto', true) | list | length > 0

- name: import ubuntu_user task
  ansible.builtin.import_tasks: user.yml
