---
defDir:
  state: "directory"
  owner: "root"
  group: "root"
  mode:  "0755"

directories:
  # raidデバイス
  raid:
  # /mnt/md0 -> see group_vars/nfs/mount.yml
  - name: "/mnt/md0"

  # nfs共有領域
  nfsShare:
  - name: "/mnt/md0/k8sCluster"

