---
defDir:
  state: "directory"
  owner: "root"
  group: "root"
  mode:  "0755"

directories:
  # raidデバイス
  raid:
  # /mnt/md0 -> see group_vars/nfs/mount.yml
  - name: "/mnt/md0"

  # nfs共有領域
  nfsShare:
  ## manifest保存用、masterノードのみ利用。
  - name:  "/mnt/md0/u6sMasters"
    owner: "1002"   # u6sMasters -> kubeope
    group: "1005"   # u6sMasters -> kubeope
    mode:  "0777"
  ## containerログ等の保管用、masterノード、workerノード両方で利用。
  - name: "/mnt/md0/u6sCluster"
    owner: "nobody"
    group: "nobody"
    mode: "0777"
