---
diskStructure:
  /dev/sda:
    - /dev/sda1
    - /dev/sda2
    - /dev/sda3
  /dev/sdb:         # for RAID1 (full)
    - /dev/sdb1     # for RAID1 (sdb1 <--> sdc1)
  /dev/sdc:         # for RAID1 (full)
    - /dev/sdc1     # for RAID1 (sdb1 <--> sdc1)
