---
defaultFileSet:
  src: "group_files/nfs/"
  owner: "root"
  group: "root"
  mode: '0644'

certification:
  - file: "root-2025.crt"
    src: "group_files/all"
    dest: "/etc/pki/ca-trust/source/anchors"

mdadmFiles:
  file: "mdadm.conf"
  path: "/etc/"

# nfs idmapd.conf
idmapdConf:
  file: "idmapd.conf"
  dest: "/etc/"

# nfs exports
exports:
  file: "exports"
  dest: "/etc/"

# chronyService:
# -> group_vars/nfs/systemd.yml

# firewalld:
# -> group_vars/nfs/systemd.yml
