---
systemdDefault:
  state: started
  enabled: true
  src: "group_files/nfs/"

chronyService:
  serviceName: chrony
  state: started
  enabled: true
  configPath: "/etc/"
  configFile: "chrony.conf"

firewalld:
  serviceName: firewalld
  state: started
  enabled: true
  configFile: "firewalld.conf"
  destZoneDir: "/etc/firewalld/zones/"
  zoneFiles:
    - srcFile: "firewalld.public.xml.j2"
      destFile: "public.xml"

nfsServer:
  serviceName: nfs-server
  state: started
  enabled: true
