---
k8s:
  cluster:
    nodeGrp: u6sCluster
  master:
    nodeGrp: u6sMasters
    repNode: u6s-master01 # kubeadm init実行ノード
    kubectlUser: kubeope
  worker:
    nodeGrp: u6sWorkers
  network:
    vhost: u6s-master
    ipaddr: "192.168.1.50"
    port: '6443'
    cidr: "10.1.0.0/16"
  kubeVip:
    URL: "https://api.github.com/repos/kube-vip/kube-vip/releases"
    imagePull: "ctr image pull ghcr.io/kube-vip/kube-vip:"
    cnRun: "ctr run --rm --net-host ghcr.io/kube-vip/kube-vip:"
  cni:
    cilium: 
      CLI:
        latestVer: "https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt"
        installPath: "/usr/local/bin"
      cilium:
        latestVer: "https://raw.githubusercontent.com/cilium/cilium/main/stable.txt"

# initialize var
# 以下はtask内で動的に設定される変数(var)を初期化するためのもの。
# taskのロジック変更がない限りはこの値は変えてはいけない。

## roles/linuxK8sBuild/tasks/main.yml
masterJoinReq: false
workerJoinReq: false