---
containerdService:
  serviceName: containerd.service
  state: started
  enabled: true
  configPath: "/etc/containerd/"
  configFile: "config.toml"
  pauseVer: "3.10"

chronyService:
  serviceName: chrony.service
  state: started
  enabled: true
  src: "group_files/u6sCluster"
  configPath: "/etc/chrony"
  configFile: "chrony.conf"
