---
aptPackages:
  - name: vim
  - name: chrony
  - name: netplan.io
  - name: containerd
  - name: apt-transport-https
  - name: ca-certificates
  - name: curl
  - name: gpg
  - name: kubeadm
    aptkey: true
    addrepo: true
    hold: true
  - name: kubelet
    aptkey: true
    addrepo: true
    hold: true
  - name: vault
  - name: nfs-common

aptPackageDefault:
  state: present
  aptkey: false
  addrepo: false
  hold: false

aptKey:
  - name: kubeadm/kubelet
    downloadURL: "https://pkgs.k8s.io/core:/stable:/v1.32/deb/"
    downloadKey: "Release.key"
    ascFile: "kubernetes-apt-keyring.asc"
    gpgFile: "kubernetes-apt-keyring.gpg"

  - name: hashicorp
    downloadURL: "https://apt.releases.hashicorp.com/"
    downloadKey: "gpg"
    ascFile: "hashicorp-archive-keyring.asc"
    gpgFile: "hashicorp-archive-keyring.gpg"

aptKeyDefault:
  dirPath: "/etc/apt/keyrings/"

aptRepo:
  - name: kubeadm/kubelet
    file: "kubernetes.list"
  - name: hashicorp
    file: "hashicorp.list"

aptRepoDefault:
  src: "group_files/u6sWorkers/repoList/"
  dest: "/etc/apt/sources.list.d/"
  owner: root
  group: root
  mode: '0644'
